<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $catBombas = Category::where('slug', 'bombas-oleohidraulicas')->first();
        $catAluminio = Category::where('slug', 'bombas-motores-aluminio')->first();
        $catElectro = Category::where('slug', 'electrovalvulas')->first();
        $catValvulas = Category::where('slug', 'valvulas-hidraulicas')->first();
        $catCilindros = Category::where('slug', 'cilindros-hidraulicos')->first();
        $catAcumuladores = Category::where('slug', 'acumuladores-filtracion')->first();
        $catIntercambiadores = Category::where('slug', 'intercambiadores-calor')->first();
        $catPartes = Category::where('slug', 'partes-accesorios')->first();
        $catCentrales = Category::where('slug', 'centrales-hidraulicas')->first();

        $products = [
            // 1. Featured Products from user HTML template
            [
                'category_id' => $catBombas->id,
                'name' => 'Bomba de Engranajes HP-X1 (Hierro Fundido)',
                'slug' => 'bomba-engranajes-hp-x1',
                'short_description' => 'Diseñada para aplicaciones móviles e industriales de alto rendimiento en cuerpo de hierro fundido.',
                'description' => 'Bomba de engranajes de alta presión fabricada en hierro fundido dúctil de alta resistencia. Ideal para maquinaria agrícola, camiones de volteo y equipos pesados de construcción.',
                'image_path' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsWcQ053IpIUfWorAGV-Cjfz1hwQehxBoFWzi93K4zdJ5ASjU1gTbkN8R5w2lPeiti_G9LAksDJy6O7DxNRQif4EmHeIdCVL6bCgmyPFjQcsKWS3ctavEjJjXmJpB6n-xTmqJ4KF4RJcdJ799Ia8-7WpLnTu7gWOT6QjzBh-gyJYsDkeEOtuGXzwuuipcjzqufasf0H6Rf6vZDlYb9G2ifCd4xQl2Z8ePrYPhg3GYhEOiXMVqAr8Ltux68uWVWI7aTQYpl-fprXg4h',
                'badge' => 'Best Seller',
                'specs' => ['Presión Máx' => '3000 PSI', 'Flujo' => '20 GPM', 'Cuerpo' => 'Hierro Fundido'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => false,
            ],
            [
                'category_id' => $catElectro->id,
                'name' => 'Válvula de Control ICV-400',
                'slug' => 'valvula-de-control-icv-400',
                'short_description' => 'Control proporcional preciso con retroalimentación electrónica integrada.',
                'description' => 'Electroválvula direccional monobloque con solenoides de alto torque y bobinas reemplazables. Excelente estanqueidad y respuesta ultrarrápida.',
                'image_path' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBwBWl0TFJqVe95q2tc5ZIpDVFwKE9kmx6RN7s2UoBmX4xzF-l0fU96_bvnnZCp3sMgDnCkdCA0rZtmcgfbRlG6wG1AvysPlsGTx776jkw40r9NCn55uvI2xkmRIo-zC8NdLt25iOkXOtBn2FoWyjaKsVD7h8tsVgW7Wd0BZWbgwDPkn31_pB1vZ0aWtjNHkbWIadvHqpFBrOhKAfZx7s_235oPU17ciPrnRtlD6sxtE-QpWYp9KBzqWPgud5JTlvuoqISVgZwg4vTf',
                'badge' => 'Destacado',
                'specs' => ['Configuración' => '4 Vías / 3 Pos', 'Voltaje' => '24V DC', 'Presión Max' => '350 Bar'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => false,
            ],
            [
                'category_id' => $catCilindros->id,
                'name' => 'Cilindro Doble Efecto DAC',
                'slug' => 'cilindro-doble-efecto-dac',
                'short_description' => 'Construcción reforzada para aplicaciones de minería y construcción.',
                'description' => 'Cilindro hidráulico de doble efecto equipado con vástago de acero cromado duro de alta resistencia al impacto y kit de sellos de poliuretano industrial.',
                'image_path' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1BKrfIVw0EJHpk26CnO7zrfgGuHgfwKFoFQeYzUUUMvLSz3qM-sryHIrEO9FKg3s--bR90uchdSfIyd_pDd58V0x9NNAw48cUyh0iObO_wFzL8nNYrk4bgi4wgEOop2lGkXQrLQZpi_4wW9-hLCgHrnbocickkSJ3IKvOWmyiXtQtFOypRmBvpmH3GyV7akN68ZdpnYOgOeInGMshZOCQwjnss0dkB-MD14VP7wCtveZxY9guF5jNy52fDTXfZiPVOfDvkDNo9f5o',
                'badge' => 'Heavy Duty',
                'specs' => ['Carrera' => '500 mm', 'Diámetro' => '120 mm', 'Montaje' => 'Ojo / Ojo'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => false,
            ],
            [
                'category_id' => $catAluminio->id,
                'name' => 'Motor Orbital SERIE-M',
                'slug' => 'motor-orbital-serie-m',
                'short_description' => 'Alto torque a bajas revoluciones para sistemas de propulsión precisos.',
                'description' => 'Motor oleohidráulico de diseño orbital compacto con válvula de disco. Diseñado para cabrestantes, barredoras, transmisiones y maquinaria pesada.',
                'image_path' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCqCi7pIbjQKmpy7Kfjz1DOASt00FFTLbZIA4XO0Bzvsf3D1Z9LPmLxxUKh4rcw-vGDGvxkBj7DdrfKiWf6qxOkIl4esmRAEPihNsthrJp29iz10kstNfmVZE1u3oBFaRvq8RwUcX6mKf8uh3Ep9zNUYXiDa_H6f3cHYm-dwOKITdD3_kB07h_mBNpYZedFpX-7UUJgyO8NM5JfZlGqIOXHjRw2xV1zFWmPd11JDrfMBRSsUI_gDDFDly3Yju-Phh92xnG0LMoj8FBQ',
                'badge' => 'Alta Eficiencia',
                'specs' => ['Torque' => '450 Nm', 'Velocidad' => '800 RPM', 'Caudal' => '60 L/min'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => false,
            ],
            [
                'category_id' => $catCentrales->id,
                'name' => 'Unidad de Potencia HPU-50',
                'slug' => 'unidad-de-potencia-hpu-50',
                'short_description' => 'Solución integral compacta con tanque de 50 litros y motor de 10HP.',
                'description' => 'Central hidráulica industrial a medida con estanque metálico de 50L, bloque manómetros, indicador de nivel de aceite y filtro de retorno integrado.',
                'image_path' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiPtGoGuHt93ATLYm1qar2fda3y4E8zJBwxvTfgfZ9Q3Z6zxLaCSaSd5jlxu0xStRC0bM0Z5OgUcMEnflAxb_KyTId7UBWtha4dEvz-HZNIipi5VuL3xK9dMWGYnv6NqTzDG2UzSd8_mHWPOZae4JZCqNBBI-C3XcIQDcwdLHPEIZnvnGVJbBd5UD3zg_X447_NQKjtd0KOL9w5VCBVzSc48WL1yD43zvYdTmh1zZDR5kcm6T56gMvoe2yH27zitgkuywsdkr8JsNj',
                'badge' => 'Heavy Duty',
                'specs' => ['Capacidad' => '50 Litros', 'Potencia' => '7.5 kW (10 HP)', 'Presión' => '210 Bar'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => false,
            ],

            // 2. Catalog Items from Brochure Image 1 & 2 (Bombas Oleohidráulicas y Válvulas)
            [
                'category_id' => $catBombas->id,
                'name' => 'Bomba Oleohidráulica de Paletas (Doble y Triple)',
                'slug' => 'bomba-oleohidraulica-de-paletas',
                'short_description' => 'Bombas simples, dobles y triples para volteo con acople directo y cardánico.',
                'description' => 'Bomba de paletas oleohidráulica para uso industrial y equipo móvil. Disponible en configuraciones simples, dobles y triples.',
                'image_path' => 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
                'badge' => 'En Stock',
                'specs' => ['Tipo' => 'Paletas', 'Acople' => 'Directo / Cardánico', 'Uso' => 'Industrial y Móvil'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catBombas->id,
                'name' => 'Bomba de Pistones de Desplazamiento Variable',
                'slug' => 'bomba-de-pistones-desplazamiento-variable',
                'short_description' => 'Bomba oleohidráulica de pistones axiales para sistemas de alta presión.',
                'description' => 'Bomba de pistones axiales de cilindrada variable. Ideal para circuitos de circuito cerrado y abierto con bajo nivel de ruido.',
                'image_path' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Alta Presión',
                'specs' => ['Presión' => '400 Bar', 'Cilindrada' => '45 cc/rev', 'Eficiencia' => '96%'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catAluminio->id,
                'name' => 'Bomba de Engranajes en Cuerpo de Aluminio Group 2',
                'slug' => 'bomba-engranajes-cuerpo-aluminio-group-2',
                'short_description' => 'Bomba compacta de aluminio para sistemas ligeros y móviles.',
                'description' => 'Cuerpo de aleación de aluminio extruido con bridas estándar SAE y DIN. Alta eficiencia volumétrica y térmica.',
                'image_path' => 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Ligera',
                'specs' => ['Cuerpo' => 'Aluminio', 'Presión Cont.' => '250 Bar', 'Velocidad' => '3500 RPM'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catValvulas->id,
                'name' => 'Válvula de Alivio y Reductora de Presión',
                'slug' => 'valvula-alivio-reductora-presion',
                'short_description' => 'Válvula hidráulica de seguridad (Relief Valve) con mando manual.',
                'description' => 'Protege el sistema de sobrepresiones. Regulable manualmente mediante perilla micrométrica graduada.',
                'image_path' => 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Seguridad',
                'specs' => ['Rango Presión' => '50 - 315 Bar', 'Caudal Máx' => '100 L/min', 'Conexión' => 'G 1/2"'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catValvulas->id,
                'name' => 'Válvula Contrabalance y Check para Cilindros',
                'slug' => 'valvula-contrabalance-check-cilindros',
                'short_description' => 'Válvula de retención pilotada y sostenimiento de carga.',
                'description' => 'Previene la caída incontrolada de la carga retenida en cilindros hidráulicos bajo tensión.',
                'image_path' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Certificada',
                'specs' => ['Ratio Piloto' => '3:1 / 4.5:1', 'Presión Máx' => '350 Bar', 'Cuerpo' => 'Acero Nitrurado'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],

            // 3. Catalog Items from Brochure Image 3 & 4 (Cilindros, Acumuladores, Intercambiadores, Repuestos)
            [
                'category_id' => $catCilindros->id,
                'name' => 'Cilindro Telescópico de 3, 4 y 5 Etapas',
                'slug' => 'cilindro-telescopico-etapas',
                'short_description' => 'Para volquetas y camiones de carga pesada con kit de empaquetaduras reforzado.',
                'description' => 'Cilindro hidráulico telescópico con etapas rectificadas y cromadas al cromo duro. Incluye kit de sellos de alta temperatura.',
                'image_path' => 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Volquetes',
                'specs' => ['Etapas' => '3 a 5 Etapas', 'Carrera Máx' => '4500 mm', 'Presión' => '170 Bar'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catCilindros->id,
                'name' => 'Tubos Honeados y Ejes Cromados para Cilindros',
                'slug' => 'tubos-honeados-ejes-cromados',
                'short_description' => 'Materia prima de alta precisión para fabricación y reparación de cilindros.',
                'description' => 'Tubos honeados en tolerancia H8/H9 y ejes o vástagos de acero 1045 con recubrimiento de cromo duro estándar y templado por inducción.',
                'image_path' => 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Materia Prima',
                'specs' => ['Material' => 'Acero ST52 / 1045', 'Tolerancia' => 'H8', 'Espesor Cromo' => '25 µm'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catAcumuladores->id,
                'name' => 'Acumulador de Nitrógeno por Vejiga y Kit de Carga',
                'slug' => 'acumulador-nitrogeno-vejiga-kit-carga',
                'short_description' => 'Acumuladores hidráulicos de vejiga y servicio de precarga de nitrógeno.',
                'description' => 'Absorbe golpes de ariete, almacena energía de emergencia y estabiliza presiones. Incluye kit de medición y manómetro con gas nitrógeno.',
                'image_path' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Mantenimiento',
                'specs' => ['Volumen' => '1.5 - 50 Litros', 'Presión Máx' => '330 Bar', 'Gas' => 'Nitrógeno N2'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catAcumuladores->id,
                'name' => 'Elementos Filtrantes Hidráulicos (Retorno y Succión)',
                'slug' => 'elementos-filtrantes-hidraulicos',
                'short_description' => 'Filtros de aceite hidráulico en celulosa, fibra de vidrio y malla metálica.',
                'description' => 'Protege componentes hidráulicos finos eliminando micropartículas de desgaste y contaminación.',
                'image_path' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Consumibles',
                'specs' => ['Filtración' => '3, 6, 10, 25 µm', 'Fluido' => 'Aceite Mineral / Sintético', 'Indicador' => 'Visual/Eléctrico'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catIntercambiadores->id,
                'name' => 'Enfriador de Aceite Hidráulico Aire-Aceite',
                'slug' => 'enfriador-aceite-hidraulico-aire-aceite',
                'short_description' => 'Intercambiadores de calor a base de aire con electroventilador 12V / 24V / 220V.',
                'description' => 'Mantiene la temperatura ideal de trabajo del sistema hidráulico evitando la degradación del aceite y fallo de sellos.',
                'image_path' => 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Alto Rendimiento',
                'specs' => ['Disipación' => 'Hasta 45 kW', 'Voltaje' => '12V / 24V / 220V', 'Mat.' => 'Aluminio Brasado'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],
            [
                'category_id' => $catPartes->id,
                'name' => 'Partes y Piezas para Bombas y Motores',
                'slug' => 'partes-piezas-bombas-motores',
                'short_description' => 'Pistones, bloques de cilindros, platos de distribución, ejes y manómetros.',
                'description' => 'Repuestos originales y alternativos de alta precisión para reparaciones de unidades hidráulicas Vickers, Rexroth, Parker, Eaton, etc.',
                'image_path' => 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Repuestos',
                'specs' => ['Marcas' => 'Vickers, Parker, Rexroth', 'Garantía' => '100% Calidad', 'Disponibilidad' => 'Inmediata'],
                'is_active' => true,
                'is_featured' => false,
                'is_service' => false,
            ],

            // 4. REPAIR SERVICES (Servicios de Reparación Especializados)
            [
                'category_id' => $catBombas->id,
                'name' => 'Reparación de Bombas Hidráulicas',
                'slug' => 'reparacion-de-bombas-hidraulicas',
                'short_description' => 'Diagnóstico en banco de pruebas y restauración completa de bombas de engranajes, paletas y pistones.',
                'description' => 'Evaluación de tolerancia, rectificado de pistas, cambio de pistones y empaquetaduras con certificación de caudal y presión en banco hidráulico.',
                'image_path' => 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Servicio Técnico',
                'specs' => ['Prueba' => 'Banco de Pruebas', 'Garantía' => '6 Meses', 'Entrega' => 'Rápida'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => true,
            ],
            [
                'category_id' => $catAluminio->id,
                'name' => 'Reparación de Motores Hidráulicos',
                'slug' => 'reparacion-de-motores-hidraulicos',
                'short_description' => 'Servicio técnico especializado para motores orbitales y de pistones de alta eficiencia.',
                'description' => 'Ajuste de distribuidores, reemplazo de rodamientos de carga axial y prueba volumétrica.',
                'image_path' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Servicio Técnico',
                'specs' => ['Inspección' => 'Micrométrica', 'Garantía' => '6 Meses', 'Servicio' => 'Especializado'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => true,
            ],
            [
                'category_id' => $catValvulas->id,
                'name' => 'Reparación de Válvulas Hidráulicas',
                'slug' => 'reparacion-de-valvulas-hidraulicas',
                'short_description' => 'Calibración y reparación de bancos de válvulas y controles proporcionales.',
                'description' => 'Rectificado de correderas, cambio de bobinas y calibración exacta del punto de alivio.',
                'image_path' => 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Calibración',
                'specs' => ['Prueba' => 'Calibración Digital', 'Bobinas' => 'Reemplazo OEM'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => true,
            ],
            [
                'category_id' => $catCilindros->id,
                'name' => 'Reparación de Cilindros Hidráulicos',
                'slug' => 'reparacion-de-cilindros-hidraulicos',
                'short_description' => 'Cambio de sellos, rectificado de vástagos y pruebas de presión certificadas.',
                'description' => 'Honeado interior de camisas, fabricación de vástagos a medida y prueba hidráulica estática a 1.5x presión de trabajo.',
                'image_path' => 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Garantizado',
                'specs' => ['Prueba' => 'Hidrostática', 'Sellos' => 'Kits Polyurethane/Viton'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => true,
            ],
            [
                'category_id' => $catCentrales->id,
                'name' => 'Reparación y Mantenimiento de Centrales Hidráulicas',
                'slug' => 'reparacion-centrales-hidraulicas',
                'short_description' => 'Mantenimiento integral de unidades de potencia, limpieza de tanques y sistemas de filtrado.',
                'description' => 'Dialisis de aceite hidráulico en sitio, lavado químico de reservorio y reemplazo de bombas y válvulas averiadas.',
                'image_path' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
                'badge' => 'Mantenimiento In-Situ',
                'specs' => ['Servicio' => 'Integral / En Sitio', 'Aceite' => 'Filtrado ISO Cleanliness'],
                'is_active' => true,
                'is_featured' => true,
                'is_service' => true,
            ],
        ];

        foreach ($products as $p) {
            Product::updateOrCreate(['slug' => $p['slug']], $p);
        }
    }
}
