import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed": "#111c2d",
                "tertiary": "#1c2739",
                "on-surface": "#191c1e",
                "error": "#ba1a1a",
                "surface-dim": "#d8dadc",
                "on-primary-container": "#b994ff",
                "on-error": "#ffffff",
                "outline": "#7b7483",
                "on-background": "#191c1e",
                "surface-tint": "#6f46b9",
                "on-tertiary": "#ffffff",
                "on-tertiary-fixed-variant": "#3c475a",
                "secondary-fixed": "#ffdad6",
                "surface-container-highest": "#e0e3e5",
                "surface-bright": "#f7f9fb",
                "secondary": "#bb0112",
                "surface": "#f7f9fb",
                "tertiary-fixed": "#d8e3fb",
                "tertiary-container": "#323d50",
                "inverse-on-surface": "#eff1f3",
                "surface-container": "#eceef0",
                "primary-container": "#4c1d95",
                "on-primary": "#ffffff",
                "on-error-container": "#93000a",
                "on-secondary-fixed": "#410002",
                "on-secondary-container": "#fffbff",
                "inverse-primary": "#d3bbff",
                "on-primary-fixed": "#260059",
                "tertiary-fixed-dim": "#bcc7de",
                "primary-fixed-dim": "#d3bbff",
                "on-secondary": "#ffffff",
                "primary": "#340075",
                "secondary-fixed-dim": "#ffb4ab",
                "on-surface-variant": "#4a4452",
                "on-primary-fixed-variant": "#572ba0",
                "surface-variant": "#e0e3e5",
                "secondary-container": "#e02928",
                "inverse-surface": "#2d3133",
                "on-tertiary-container": "#9ca8be",
                "background": "#f7f9fb",
                "on-secondary-fixed-variant": "#93000b",
                "surface-container-high": "#e6e8ea",
                "surface-container-low": "#f2f4f6",
                "outline-variant": "#ccc3d4",
                "primary-fixed": "#ebdcff",
                "surface-container-lowest": "#ffffff",
                "error-container": "#ffdad6"
            },
            spacing: {
                "md": "16px",
                "xl": "40px",
                "sm": "8px",
                "margin-desktop": "64px",
                "base": "4px",
                "margin-mobile": "16px",
                "xs": "4px",
                "gutter": "24px",
                "lg": "24px"
            },
            fontFamily: {
                "body-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "body-md": ["Inter", ...defaultTheme.fontFamily.sans],
                "mono-data": ["Geist", "monospace"],
                "display": ["Hanken Grotesk", ...defaultTheme.fontFamily.sans],
                "headline-lg": ["Hanken Grotesk", ...defaultTheme.fontFamily.sans],
                "label-caps": ["Geist", "sans-serif"],
                "headline-lg-mobile": ["Hanken Grotesk", ...defaultTheme.fontFamily.sans],
                "headline-md": ["Hanken Grotesk", ...defaultTheme.fontFamily.sans],
                "body-sm": ["Inter", ...defaultTheme.fontFamily.sans]
            }
        },
    },
    plugins: [],
};
